[workspace]
resolver = "2"

members = [
    "mandelbrot",
    "shader-builder",
    "shaders/mandelbrot",
    "shaders/textures",
    "shaders/triangle",
    "textures",
    "triangle",
    "viewport",
]
